name: Render video
on:
  workflow_dispatch:
    inputs:
      brandImg:
        default: ""
        required: true
        description: "test"
      heroImg:
        default: "https://assets.kogan.com/files/product/2021/FS700CALTHA/FS700CALTHA_3.jpg?auto=webp&canvas=1080%2C1920&fit=bounds&height=1920&quality=75&width=1080"
        required: true
        description: "test"
      firstImg:
        default: ""
        required: true
        description: "test"
      productTitle:
        default: "Product title"
        required: true
        description: "test"
      salePriceDollars:
        default: "00"
        required: true
        description: "test"
      salePriceCents:
        default: "00"
        required: false
        description: "test"
      papDollars:
        default: "00"
        required: true
        description: "test"
      papCents:
        default: "00"
        required: false
        description: "test"
      heroDimensions:
        default: "196.921875, -43.828125, 1"
        required: true
        description: "test"
      simpleDate:
        default: "2022-08-31"
        required: true
        description: "test"
jobs:
  render:
    name: Render video
    runs-on: macos-12
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
      - run: brew install ffmpeg
      - run: npm i
      - run: echo $WORKFLOW_INPUT > input-props.json
        env:
          WORKFLOW_INPUT: ${{ toJson(github.event.inputs) }}
      - run: npm run build -- --props="./input-props.json"
      - uses: actions/upload-artifact@v2
        with:
          name: video.mp4
          path: out/video.mp4
